import type { Metadata } from "next";
import {
  ClerkProvider,
} from "@clerk/nextjs";
import localFont from "next/font/local";
import "./globals.css";
import { Footer } from "./components/footer";
import { Nav } from "./components/nav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "QRate Reviews: Experience the power of customer reviews.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      signInUrl="/auth/sign-in"
      signUpUrl="/auth/sign-up"
    >
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Nav />
          <div className="">{children}</div>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
